### ISSUE TITLE
CMS Editor Content Style

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#11]
Hi,

Daniel we are using tinymce editor in CMS side. But it acts weird sometimes, for example some html5 tags are skipped as default behaviour (like figure, article, etc). 

I notice that also 

<a href="#" class="a">
    <div> AAAA </div>
</a>

type coding also not working. I mean it skips anchor link. I thought that is is about the version of tinymce because it is really an old one. So i checked with latest version and still same issue. Another common editor is ckeditor. It solves the issue, I mean it does not skip anchor link but it replaces the tags. That is,

<div><a href="#" class="a">AAAA</a></div> 

the result which is not the original thing.

I will google it a little bit more but could you suggest anything? Or could we change the structure of coding a little bit with same output as result.

**Comment by kenan-memis** [comment]
Ok daniel  I solved the problem.. Tinymce has an init property named valid_children. I add a a[div] style definition and solved the problem.

**Comment by ldanielswakman** [comment]
Okay good to hear! This can be an annoying issue with CMS'es stripping out html tags... maybe there is even an option to parse all content as html code...
