### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#14]
Hi,

Daniel is it possible to change pagination styling from 

``` html
<ul class="list-pagination clearfix">
  <li><a href="#"><i class="icon icon-arrows-left icon-15x u-floatleft"></i></a></li>
  <li><a href="#">1</a></li>
  <li class="active"><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#"><i class="icon icon-arrows-right icon-15x u-floatleft"></i></a></li>
</ul>
```

to something

``` html
<div class="pagination">
    <span class="previous_page disabled">← Previous</span> 
    <em class="current">1</em> 
    <a rel="next" href="/announcements?page=2">2</a> 
    <a class="next_page" rel="next" href="/announcements?page=2">Next →</a>
</div>
```

If it is please change it because i have to make huge implementation in order to customize pagination library.

**Comment by ldanielswakman** [comment]
Kenan this is okay for me to do in principle, I'm just awaiting the outcome of some communication between me and Ceren before doing more of this work; will keep you updated

**Comment by ldanielswakman** [comment]
https://github.com/ldanielswakman/nttd-design/commit/e2f92e84b3aaffd8dbb0a545673db23c6cecd4ba
