### ISSUE TITLE
News-Show Images

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#15]
Hi,

news-show page will be used both for news and events, with small changes. Last time we have talked about event or news image. If you could also add that image  (as Ceren gave the example of http://www.hollanduktrade.nl/actueel/evenementen/event/trends-in-advanced-mach) part above the content it would be great. There are also other images, I think they can add up to 5 images but this is not the current concern. We can think about it later but at least for one main image a new part is required and the top is a good fit I guess.

**Comment by kenan-memis** [comment]
For example http://nttd.com.tr/en/announcements/51-seminar-on-the-new-turkish-commercial-code-10-april-2012 this is an old announcement. At the bottom there are the other images uploaded. 

And this is another example with main image
http://nttd.com.tr/en/announcements/15-csr-principles-in-international-business

**Comment by ldanielswakman** [comment]
https://github.com/ldanielswakman/nttd-design/commit/66c04fc48b0bfabac76a411e8986e1d7566b5f6c
