### ISSUE TITLE
Header Issue While Scrolling Down

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#4]
Hi,

I noticed that there is a blank are (probably blank margin) between the top of header and top of browser screen while scrolling down.

**Comment by ldanielswakman** [comment]
Are you talking about this area? Because that one is intentional since the whole body has an offset padding of 20px.

![margin](https://cloud.githubusercontent.com/assets/4538367/11020709/5e88b386-8630-11e5-9531-27e70d042c91.jpg)

**Comment by kenan-memis** [comment]
But could not you remove padding-top part? Or do somethig? If you scroll a
little bit more then you can see the content text is scrolling upwords
between the top part and that menu. It is not a good view. Ceren probably
would tell you about this.

**Comment by ldanielswakman** [comment]
Ah okay I understand; yeah the fact that the content was visible behind the header was a temporary bug (since a menu style fix); that should be fixed in the latest commit.

**Comment by kenan-memis** [comment]
Okey :)
