### ISSUE TITLE
Icons for trade directory

### ISSUE THREAD

**Issue by ldanielswakman** [ldanielswakman/nttd-design#5]
| Letter | Name | Icon |
| --- | --- | --- |
| [A] | Agriculture, forestry and fishing | icon-basic-flag2 |
| [B] | Mining and quarrying | icon-basic-hammer |
| [C] | Manufacturing | icon-basic-settings |
| [D] | Electricity, gas, steam and air conditioning supply | icon-basic-bolt |
| [E] | Water supply; sewerage; waste managment and remediation activities | icon-weather-drop |
| [F] | Construction | icon-basic-pencil-ruler |
| [G] | Wholesale and retail trade; repair of motor vehicles and motorcycles | icon-ecommerce-cart-content |
| [H] | Transporting and storage | icon-arrows-switch-horizontal |
| [I] | Accommodation and food service activities | icon-basic-clubs |
| [J] | Information and communication | icon-basic-message-txt |
| [K] | Financial and insurance activities | icon-ecommerce-graph3 |
| [L] | Real estate activities | icon-basic-home |
| [M] | Professional, scientific and technical activities | icon-basic-lightbulb |
| [N] | Administrative and support service activities | icon-basic-todo-txt |
| [O] | Public administration and defence; compulsory social security | icon-basic-lock |
| [P] | Education | icon-software-pen |
| [Q] | Human health and social work activities | icon-basic-heart |
| [R] | Arts, entertainment and recreation | icon-music-playlist |
| [S] | Other services activities | icon-basic-sheet |
| [T] | Activities of households as employers; undifferentiated goods | icon-basic-case |
| [U] | Activities of extraterritorial organisations and bodies | icon-basic-world |

**Comment by kenan-memis** [comment]
Hi Daniel,

Two of the icons related to Construction Sector and Arts, entertainment and recreation Sector are not visible. Could you please check it?

http://beta2016.nttd.com.tr/directory
