### ISSUE TITLE
About us > Our Services

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#6]
Hi,

Daniel  could you change the bullets down the page to expandable parts? Like FAQ page, istead arrows you can use + and - signs. You know it better than me, so if you could add also this part, then I will finish all the About Us pages.

**Comment by ldanielswakman** [comment]
Yesterday during the meeting we agreed we would not make expandable/collapsible sections, but  instead provide same-page links with scrolling. I've done a bit of quick content design, adding an icon and arranging the sections in 2 columns. See commit 18afdc7 in repo
